id: faae40c5-7bbe-4bcc-831f-597c20e23959
title: '1080p OldManKain - Resolution -1.1.1 -FXAA'
subtitle:
description:
version:
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

