id: cd7304b6-b01a-428c-9b44-8dbbe0b047b3
title: Lazy Pack - 60 FPS - 1440p 2X - 2880p 4X - UI Mod Compatible
subtitle: 'it just werks'
description: Combination of over a dozen patches. Compatible with most mods. Use UI Mod Compatible version if you want to use a controller mod such as Playstation UI.
version: 3.0.0
category: 6
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author: 
    - { name: 'ChucksFeedAndSeed, Marethyu, Wollnashorn, Patchanon, somerandompeople, bad1dea, OldManKain, Sweetmini, MaxLastBreath' }
    