id: a1345bf5-130a-4f78-baf4-4e32dc2706fe
title: Infinite Health
subtitle:
description:
version: 1.2.0
category: 5
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author:
  -  { name: 'bad1dea', link: 'https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom' }
