id: bc4f88d8-fcbd-4ce3-a193-9bb3f772eb3b
title: Anisotropic Filtering Fix
subtitle:
description:
version: 1.0.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

