id: 05915cd4-58b6-438b-9566-868d76893bb5
title: Aspect ratio - 256-135
subtitle:
description:
version: 1.0.0
category: 3
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
author:
  - { name: 'Fayaz', link: 'https://gamebanana.com/mods/updates/443462' }
  - { name: 'Fruithapje21', link: 'https://github.com/Fruithapje21/TOTK-Ultrawide' }