id: f7240190-ebfa-4eda-8406-6c532accbf27
title: Shadows - 256x - performance boost
subtitle:
description:
version: 1.0.2
category: 2
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
  - { name: 'somerandompeople', link: https://gbatemp.net/download/loz-tears-of-the-kingdom-20fps-30fps-60fps-patch.37996/ }
  - { name: 'StevenssND' }

