id: ab613059-9e0e-4ba8-80d4-7cb9260a5358
title: Sweetmini 1008p
subtitle: FXAA Off - Includes FSR and DynRes Disabler - Zero AO Bugs
description:
version: 1.0.1
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
    - 0ef8f231-8d97-486e-bfa1-e40f578eed9d
    - d356a7a2-4e8f-4187-8321-7f4d56d1a2f6
author: 
  - name: Sweetmini

