id: 73f78aec-ca9b-4480-b7d5-fc534d85183e
title: Disable Internal FXAA v2
subtitle:
description:
version: 2.0.1
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
  - { name: Sweetmini, link: }

