id: 308d7e93-beeb-4bd1-98bb-fe6b1a026eb8
title: Attack Speed (1.5x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

