id: 5c786dfe-2157-4720-ad3b-235c3dba51ff
title: Pickup Sell Buy (2x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

