id: 894389fb-4122-43e5-95f4-6fc2ae921524
title: Stealth always on
subtitle:
description:
version: 1.2.0
category: 5
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author:
  - {  name: NXCheats, link: https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20v262144%20for%20Yuzu }

