id: 762bd93b-8612-45a6-8b86-5f7f8ed28156
title: Aspect ratio - 19.5-9
subtitle: iPhone
description:
version: 1.0.0
category: 3
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
author:
  - { name: 'Fayaz', link: 'https://gamebanana.com/mods/updates/443462' }
  - { name: 'Fruithapje21', link: 'https://github.com/Fruithapje21/TOTK-Ultrawide' }