id: 62ba7b3a-052e-457e-9424-bcf57ce75171
title: UI Blackscreen Fix
subtitle:
description:
version: 1.0.1
category: 1
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author: 
  - name: MarethyuX