id: c8a917b0-1401-49cc-b959-f2693db7432b
title: Infinite Durability (Fire will still break it.)
subtitle:
description:
version: 1.2.0
category: 5
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author:
  -  { name: 'bad1dea', link: 'https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom' }
