id: b9341a97-0b7c-4d04-ae42-299f69f7db7b
title: Remove Lens Flare
subtitle:
description:
version: 1.0.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.1
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

