id: a986a6d6-6481-4af1-8573-53025396b99e
title: Shadows - 512x - performance boost
subtitle:
description:
version: 1.0.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

