id: 6011a011-9cd0-4e7f-9d20-556b8b697c8f
title: 1026p - FXAA Off
subtitle:  FXAA Off - Disables FSR filter and scaler and DynRes - Bug, AO flickers in shadow
description:
version: 1.0.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.1
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

