id: 61e1a7e1-bddb-4352-92a3-4d0e23382c68
title: Shadows - 1024x - highest stable
subtitle:
description:
version: 1.0.1
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

