id: 9908e2a4-91b4-41a2-b16e-10c1974885af
title: Sweetmini 1008p
subtitle: FXAA On - Includes FSR and DynRes Disabler  - Zero AO Bugs
description:
version: 1.0.1
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
    - 0ef8f231-8d97-486e-bfa1-e40f578eed9d
    - d356a7a2-4e8f-4187-8321-7f4d56d1a2f6
author: 
  - name: Sweetmini

