id: b52789aa-507d-4209-87c3-3c88661385e5
title: God-mode (Ignore Hits)
subtitle:
description:
version: 1.1.2
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
author:
  - {  name: NXCheats, link: https://github.com/bad1dea/NXCheats/tree/main/The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom/0100F2C0115B6000%20v262144%20for%20Yuzu }

