id: c9910667-cce7-4059-abd6-ca3b24b98128
title: Pickup Sell Buy (10x)
subtitle:
description:
version: 1.1.0
category: 5
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:

