id: 56918512-a997-4b32-aef1-3717e9dc89f0
title: Aspect ratio - 4-3
subtitle:
description:
version: 1.0.0
category: 3
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
  - { name: Fayaz, link: https://gamebanana.com/mods/updates/443462 }

